# Generated by Django 2.2 on 2020-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRatesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('USD', 'usd'), ('EUR', 'eur'), ('JPY', 'jpy'), ('HUF', 'huf'), ('CHF', 'chf')], default='USD', max_length=3)),
                ('purchase_rate', models.PositiveIntegerField()),
                ('sale_rate', models.PositiveIntegerField()),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
            ],
            options={
                'ordering': ('-valid_from',),
            },
        ),
    ]
