# Generated by Django 2.2 on 2020-02-18 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasco_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyratesmodel',
            name='purchase_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-12)]),
        ),
        migrations.AlterField(
            model_name='currencyratesmodel',
            name='sale_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-12)]),
        ),
    ]
